"use strict";
const upsert = require('../utils/upsert');
module.exports.seed = function(knex,Promise){
    let rows =[
        {
            id:1,
            name:'Challenger',
            Game_id:1
        },
        {
            id:2,
            name:'Rival',
            Game_id:1
        },
        {
            id:3,
            name:'Duelist',
            Game_id:1
        },
        {
            id:4,
            name:'Gladiator',
            Game_id:1
        },
        {
            id:5,
            name:'Bronze',
            Game_id:2
        },
        {
            id:6,
            name:'Silver',
            Game_id:2
        },
        {
            id:7,
            name:'Gold',
            Game_id:2
        },
        {
            id:8,
            name:'Platinum',
            Game_id:2
        },
        {
            id:9,
            name:'Diamond',
            Game_id:2
        },
        {
            id:10,
            name:'Bronze',
            Game_id:3
        },
        {
            id:11,
            name:'Silver',
            Game_id:3
        },
        {
            id:12,
            name:'Gold',
            Game_id:3
        },
        {
            id:13,
            name:'Platinum',
            Game_id:3
        },
        {
            id:14,
            name:'Diamond',
            Game_id:3
        },
        {
            id:15,
            name:'Master',
            Game_id:3
        },
        {
            id:16,
            name:'Grandmaster',
            Game_id:3
        },
    ];
    return Promise.all(rows.map(row=>{
        return;
        //return upsert(knex,'Rank',row);
    }));
};
